### ISSUE TITLE
Mario can clip/sink through some slopes on the BITFS scaling platform

### ISSUE THREAD

**Issue by Arceveti** [Reonu/HackerSM64#200]
In BITFS, jumping down onto one of the two middle slopes on the scaling platform as it expands, while moving in the uphill direction in the slope, sometimes causes Mario to clip downwards into the floor and get stuck in place, seeming to "sink" through it as it continues to expand upwards.
![image](https://user-images.githubusercontent.com/73617174/146605511-98208595-59d2-49fb-b050-497a07ee7b70.png)
It's easiest to reproduce by doing a side flip onto one of those two slopes (in the uphill direction) while the platform is halfway expanded.

**Comment by arthurtilly** [comment]
Can confirm this is not an issue in vanilla decomp with only PD2 applied. (also, that's BitFS, not LLL)

**Comment by Arceveti** [comment]
> Can confirm this is not an issue in vanilla decomp with only PD2 applied. (also, that's BitFS, not LLL)

Fixed, thanks lol

**Comment by Arceveti** [comment]
Fixed the title, not the issue itself, I mean

**Comment by arthurtilly** [comment]
Also can confirm that this issue still happens with PD2 disabled. not my fault B)

**Comment by thecozies** [comment]
The fix causes smashing objects to not work

**Comment by thecozies** [comment]
https://user-images.githubusercontent.com/79979276/147386667-330308d1-bb7c-4460-8d66-04e17652a43c.mp4

https://user-images.githubusercontent.com/79979276/147386670-814024e0-872c-40fc-9472-e3542bd12c9e.mp4


https://user-images.githubusercontent.com/79979276/147386678-76c6402e-5729-40bf-9897-6ca90cbd9f37.mp4

**Comment by thecozies** [comment]
hopefully actually fixed
